### ISSUE TITLE
[BUG] Can't load mirador from local.

### ISSUE THREAD

**Issue by rosiel** [Islandora/islandora_mirador#26]
**What steps does it take to reproduce the issue?**

* Set Config > Media > Mirador settings to load mirador from "Local library".
* Place a copy of main.js in web/libraries/mirador/dist (created by running `npm run webpack` in the [mirador-integration](https://github.com/roblib/mirador-integration-islandora) repo
* Load a page that loads mirador

## What happens?

The mirador library is loaded from roblib.github.io, as seen in the Network tab of a Firefox Inspector pane.

* To whom does it occur (anonymous visitor, editor, administrator)?
Everyone, I presume

* What did you expect to happen?
It would load from "local library"

**Which version of Islandora are you using?**
modern

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by wgilling** [comment]
At the tech call, Seth et.al. suggested that the reason this is happening is due to the mirador coming from roblib being hard-coded somewhere... and that that issue would obviously be something that would be a blocker for the mirador work @alxp has been working on.

**Comment by alxp** [comment]
This seems to be due to two things:

1. It's confusing where to actually put Mirador as a local library and what it should be called.
2. 2. The libraries alter hook was not unsetting the remote location. In older versions of Drupal, it seemed to be loading the library from the last array entry in $libraries['mirador']['js'], but in my Drupal 10 this isn't working.

PR to come.
